---
- name: Update microk8s to latest stable version
  hosts: '{{ host_target }}'
  gather_facts: false
  become: true
  collections:
  - community.general

  tasks:
  - name: Ping all hosts
    ansible.builtin.ping:

  - name: Run Snap Refresh microk8s
    community.general.snap:
      name: microk8s
      state: present
      classic: true
      channel: '{{ microk8s_version }}'
  
  - name: Restart each VM
    ansible.builtin.reboot: